[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run meteolabx.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10